# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("6.10.0")


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"


# include: "rules/process_reads.smk"


# declare https://github.com/b-brankovics/smkwf-oligo-screening as a module
module smkwf_oligo_screening:
    snakefile:
        github(
            "b-brankovics/smkwf-oligo-screening",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


# use all rules from https://github.com/b-brankovics/smkwf-oligo-screening
use rule * from smkwf_oligo_screening exclude all


# Add STR typing specific rules
rule str_typing:
    input:
        tsv="results/{sample}/result.tsv",
        STR="config/STR.tsv",
    output:
        "results/{sample}/str_repeats.tsv",
    log:
        "logs/str_typing/{sample}.log",
    conda:
        "envs/pandas.yaml"
    script:
        "scripts/str_count.py"


rule str_overview:
    input:
        counts=expand("results/{sample}/str_repeats.tsv", sample=samples),
    output:
        "results/str_overview.tsv",
        "results/str_multi.tsv",
    log:
        "logs/str_overview.log",
    conda:
        "envs/pandas.yaml"
    script:
        "scripts/str_overview.py"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        expand("results/{sample}/result.tsv", sample=samples),
        expand("results/{sample}/amplicons.fas", sample=samples),
        "results/str_overview.tsv",
        "results/str_multi.tsv",
