# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("6.10.0")


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
# include: "rules/common.smk"
# include: "rules/process_reads.smk"

# declare https://github.com/b-brankovics/smkwf-oligo-screening as a module
module smkwf_oligo_screening:
    snakefile: 
        github("b-brankovics/smkwf-oligo-screening", path="workflow/Snakefile", branch="setup")
    config:
        config


# use all rules from https://github.com/b-brankovics/smkwf-oligo-screening
use rule * from smkwf_oligo_screening exclude all


# Add STR typing specific rules
rule str_typing:
    input:
        tsv="results/{sample}/result.tsv",
        STR="config/STR.tsv"
    output:
        "results/{sample}/str_repeats.tsv"
    # conda:
    #     "envs/primers.yml"
    log:
        "logs/str_typing/{sample}.log"
    script:
        "scripts/str_count.py"


rule str_overview:
    input:
        counts=expand("results/{sample}/str_repeats.tsv", sample=config["samples"])
    output:
        "results/str_overview.tsv",
        "results/str_multi.tsv"
    # conda:
    #     "envs/primers.yml"
    log:
        "logs/str_overview.log"
    script:
        "scripts/str_overview.py"

# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        expand("results/{sample}/result.tsv", sample=config["samples"]),
        expand("results/{sample}/amplicons.fas", sample=config["samples"]),
        "results/str_overview.tsv"
    default_target: True
